CREATE SEQUENCE MYSQ
 START WITH     1
 INCREMENT BY   1
 NOMAXVALUE
 NOCACHE
 NOCYCLE;

--회원가입
CREATE OR REPLACE PROCEDURE MEMBER_INSERT(VID IN MEMBER.MEMBER_ID%TYPE,
VPW IN MEMBER.PASSWORD%TYPE,
VFID IN MEMBER.FAMILY_ID%TYPE,
VNN IN MEMBER.NICKNAME%TYPE)
IS

BEGIN
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, PASSWORD, FAMILY_ID, NICKNAME, INDATE) VALUES(MYSQ.NEXTVAL, VID, VPW, VFID, VNN, SYSDATE);
END;
/


--로그인 확인
CREATE OR REPLACE FUNCTION MEMBER_LOGIN(VID IN MEMBER.MEMBER_ID%TYPE,
VPW IN MEMBER.PASSWORD%TYPE) RETURN NUMBER
IS
DBPW MEMBER.PASSWORD%TYPE := NULL;
EXISTS_NUM NUMBER := 0;

BEGIN
 
SELECT CASE 
WHEN EXISTS (SELECT MEMBER_ID FROM MEMBER WHERE MEMBER.MEMBER_ID = VID)  THEN 1
ELSE 0 
END 
INTO EXISTS_NUM FROM DUAL;

IF EXISTS_NUM = 1 THEN  
SELECT PASSWORD INTO DBPW
FROM MEMBER
WHERE MEMBER_ID = VID;
IF DBPW = VPW THEN
RETURN 1;
ELSE
RETURN 0;
END IF;
ELSIF EXISTS_NUM = 0 THEN
RETURN 0;
END IF;
END;
/
